language: ruby
sudo: false
rvm:
  - 2.2
env:

services:
  - postgresql

branches:
  only:
    - master

env:
  - DB=postgresql

  before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

