
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: 5

# development:
#   <<: *default
#   database: shoppe_development

# test:
#   <<: *default
#   database: shoppe_test

# production:
#   <<: *default
#   database: shoppe_production
#   username: shoppe
#   password: <%= ENV['SHOPPE_DATABASE_PASSWORD'] %>

default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
development:
  <<: *default
  database: db/development.sqlite3
test:
  <<: *default
  database: db/test.sqlite3
production:
  <<: *default
  database: db/production.sqlite3
